export const metricsById = {
  draftYear: { value: 'draftYear', label: 'Draft Year' },
  draftPick: { value: 'draftPick', label: 'Draft Pick' },
  seasons: { value: 'seasons', label: 'Seasons' },
  gp: { value: 'gp', label: 'Games Played' },
  min: { value: 'min', label: 'Minutes' },
  pts: { value: 'pts', label: 'Points' },
  trb: { value: 'trb', label: 'Rebounds' },
  ast: { value: 'ast', label: 'Assist' },
  fgpct: { value: 'fgpct', label: 'FG%' },
  fg3pct: { value: 'fg3pct', label: '3PT FG%' },
  ftpct: { value: 'ftpct', label: 'FT%' },
  minpg: { value: 'minpg', label: 'Minutes per game' },
  ptspg: { value: 'ptspg', label: 'Points per game' },
  trbpg: { value: 'trbpg', label: 'Rebounds per game' },
  astpg: { value: 'astpg', label: 'Assists per game' },
  ws: { value: 'ws', label: 'Win Shares' },
  wsper48: { value: 'wsper48', label: 'Win Shares per 48' },
  bpm: { value: 'bpm', label: 'BPM' },
  vorp: { value: 'vorp', label: 'VORP' },
};

export default [
  metricsById.draftYear,
  metricsById.draftPick,
  metricsById.seasons,
  metricsById.gp,
  metricsById.min,
  metricsById.pts,
  metricsById.trb,
  metricsById.ast,
  metricsById.fgpct,
  metricsById.fg3pct,
  metricsById.ftpct,
  metricsById.minpg,
  metricsById.ptspg,
  metricsById.trbpg,
  metricsById.astpg,
  metricsById.ws,
  metricsById.wsper48,
  metricsById.bpm,
  metricsById.vorp,
];
